name: Test deploy
on:
  push:
    branches:
      - main
jobs:
  ssh:
    name: SSH into test EC2 Instance
    runs-on: ubuntu-latest
    steps:
    - name: Executing git commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_SITE }}
        port: ${{ secrets.PORT }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.GROUP_13_SECRET }}
        script: |
          cd /var/www/html
          git pull origin master
