domain.com:
  hostname: 54.153.156.106
  user: bitnami
  port: 22
  configFile: ~/.ssh/config
  identityFile: ~/.ssh/id_rsa_github
  forwardAgent: true
  multiplexing: true
  sshOptions:
    UserKnownHostsFile: /dev/null
    StrictHostKeyChecking: no
  stage: production
  roles:
    - app
    - db
  deploy_path: ~/app
